# Базовые настройки
  title: "Party Legend: Legal Documents"
  description: "Terms & Conditions and Privacy Policy for iOS app"

  # Убрать название репозитория из заголовка
  show_downloads: false

  # Настройки темы
  github:
  is_project_page: false
  is_user_page: false
