# Базовые настройки
  title: "Party Legend: Legal Documents"
  description: "Terms & Conditions and Privacy Policy for Party Legend iOS 
  app"

  # Убрать название репозитория из заголовка
  show_downloads: false

  # Использовать чистую тему
  theme: jekyll-theme-cayman

  # Настройки темы
  github:
  is_project_page: false
  is_user_page: false
