# Базовые настройки
  title: "Party Legend: Legal Documents"
  description: "Terms & Conditions and Privacy Policy"

  # Убрать название репозитория из заголовка
  show_downloads: false

  # Использовать чистую тему
  theme: jekyll-theme-minimal

  # Настройки темы
  github:
  is_project_page: false
  is_user_page: false
